// GENERATED by HomeScreen/scripts/dump_wire_fixture.py -- do not edit.
//
// The exact bytes the server emits. Regenerate with:
//   venv/bin/python scripts/dump_wire_fixture.py
// tests/test_wire_contract.py fails if this drifts from the server.
#pragma once

inline constexpr char kWireAssigned[] = R"JSON({"assigned":true,"components":[{"c":"radar","feed_age_s":0.0,"feed_ok":true,"items":[{"age":3.1,"alt":"3675 ft","cs":"IBE3221","dst":7.4,"gs":400.0,"lat":40.49556,"lon":-3.67836,"nose":90.0,"trk":91.0,"ty":"A320","ve":0.13,"vn":-0.17},{"age":0.4,"alt":"12000 ft","cs":"RYR44BQ","dst":12.9,"gs":250.0,"lat":40.41556,"lon":-3.73836,"nose":270.0,"trk":271.0,"ty":"B738","ve":-0.09,"vn":0.02}],"radius_km":60.0}],"hw":"aabb00112233","layout":"fill","name":"radar","scene":"planes"})JSON";
inline constexpr char kWireUnassigned[] = R"JSON({"assigned":false,"components":[],"hw":"aabb00112233","layout":"fill","message":"sin asignar · elige una escena en el panel","name":null,"scene":"unassigned"})JSON";
inline constexpr char kWirePending[] = R"JSON({"assigned":false,"components":[],"hw":"aabb00112233","layout":"fill","message":"esperando aprobación · apruébalo en el panel","name":null,"scene":"pending"})JSON";
inline constexpr char kWireDropped[] = R"JSON({"assigned":true,"components":[],"hw":"aabb00112233","layout":"fill","name":"radar","scene":"planes","unsupported":["radar"]})JSON";

// ok:false, data fresh -- a single upstream timeout. Must NOT blank.
inline constexpr char kWireFeedDown[] = R"JSON({"assigned":true,"components":[{"c":"radar","feed_age_s":0.0,"feed_ok":false,"items":[{"age":3.1,"alt":"3675 ft","cs":"IBE3221","dst":7.4,"gs":400.0,"lat":40.49556,"lon":-3.67836,"nose":90.0,"trk":91.0,"ty":"A320","ve":0.13,"vn":-0.17},{"age":0.4,"alt":"12000 ft","cs":"RYR44BQ","dst":12.9,"gs":250.0,"lat":40.41556,"lon":-3.73836,"nose":270.0,"trk":271.0,"ty":"B738","ve":-0.09,"vn":0.02}],"radius_km":60.0}],"hw":"aabb00112233","layout":"fill","name":"radar","scene":"planes"})JSON";
// ok:TRUE, 90s stale -- the fetch daemon was stopped and nothing ever
// wrote a failure. The only signal is feed_age_s. MUST expire.
inline constexpr char kWireFeedStale[] = R"JSON({"assigned":true,"components":[{"c":"radar","feed_age_s":90.0,"feed_ok":true,"items":[{"age":93.1,"alt":"3675 ft","cs":"IBE3221","dst":7.4,"gs":400.0,"lat":40.49556,"lon":-3.67836,"nose":90.0,"trk":91.0,"ty":"A320","ve":0.13,"vn":-0.17},{"age":90.4,"alt":"12000 ft","cs":"RYR44BQ","dst":12.9,"gs":250.0,"lat":40.41556,"lon":-3.73836,"nose":270.0,"trk":271.0,"ty":"B738","ve":-0.09,"vn":0.02}],"radius_km":60.0}],"hw":"aabb00112233","layout":"fill","name":"radar","scene":"planes"})JSON";

// Echoed verbatim in If-None-Match, HTTP quotes included.
inline constexpr char kWireAssignedEtag[] = "\"d7c9772d3c900aa7\"";
inline constexpr int kWireAssignedPollSeconds = 5;

// Where the fixture traffic is. A test whose radar centre is anywhere
// else clips every target off the dial and proves nothing.
inline constexpr double kWireHomeLat = 40.445564;
inline constexpr double kWireHomeLon = -3.698361;
