"""Emit the firmware's wire fixture from THIS server's own routes.

The firmware parses bytes this server produces. A fixture hand-written on the
firmware side drifts the moment a field is renamed, and the failure shows up as
a blank screen on hardware rather than a red test. So it is generated, checked
in, and pinned from both sides by tests/test_wire_contract.py.
"""
import argparse
import json
import pathlib
import sys
import tempfile
from datetime import datetime, timezone

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from homescreen.serve import create_app          # noqa: E402

CFG = {"location": {"name": "Madrid", "timezone": "Europe/Madrid"},
       "feeds": {"adsb": {"source": "api", "endpoint": "https://x"}},
       "devices": []}
HW = "aabb00112233"
QUERY = "w=240&h=240&depth=16&max_items=40&components=radar&fw=hs-0.1"
NOW = 1_787_000_000.0
#: The radar centre the firmware's tests use. Targets must be near it or the
#: renderer clips them off the dial and a drawing test proves nothing.
HOME_LAT, HOME_LON = 40.445564, -3.698361
AIRCRAFT = [
    # ve/vn are deliberately NOT consistent with gs/trk: a firmware that
    # recomputes them from gs and track instead of reading them fails a test.
    {"lat": HOME_LAT + 0.05, "lon": HOME_LON + 0.02, "nose": 90.0, "trk": 91.0,
     "gs": 400.0, "ve": 0.13, "vn": -0.17, "age": 3.1, "dst": 7.4,
     "cs": "IBE3221", "ty": "A320", "alt": "3675 ft"},
    {"lat": HOME_LAT - 0.03, "lon": HOME_LON - 0.04, "nose": 270.0,
     "trk": 271.0, "gs": 250.0, "ve": -0.09, "vn": 0.02, "age": 0.4,
     "dst": 12.9, "cs": "RYR44BQ", "ty": "B738", "alt": "12000 ft"},
]


def _write_feed(cache_dir: pathlib.Path, fetched_at: float,
                ok: bool = True) -> None:
    path = cache_dir / "feed" / "adsb.json"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps({
        "fetched_at": datetime.fromtimestamp(fetched_at,
                                             timezone.utc).isoformat(),
        "ok": ok, "error": None, "data": {"aircraft": AIRCRAFT}}))


def build(out_path: pathlib.Path) -> None:
    cache_dir = pathlib.Path(tempfile.mkdtemp())
    app = create_app(CFG, cache_dir, version="fixture", clock=lambda: NOW)
    client = app.test_client()
    _write_feed(cache_dir, NOW)

    # First contact: registered, but nobody has let it into the fleet yet.
    pending = client.get(f"/api/devices/{HW}/scene?{QUERY}")
    client.put(f"/api/devices/{HW}/membership", json={"approved": True})
    # Admitted, but not yet given a job. A different screen and a different
    # message, and the firmware has to tell them apart -- so both are pinned.
    unassigned = client.get(f"/api/devices/{HW}/scene?{QUERY}")
    client.patch(f"/api/devices/{HW}", json={"name": "radar", "scene": "planes"})
    assigned = client.get(f"/api/devices/{HW}/scene?{QUERY}")
    dropped = client.get(
        f"/api/devices/{HW}/scene?w=240&h=240&depth=16&components=text")

    # ok:false with fresh data -- one upstream timeout. The device must NOT
    # blank on this; write_failure keeps the last good aircraft.
    client.get(f"/api/devices/{HW}/scene?{QUERY}")          # re-declare radar
    _write_feed(cache_dir, NOW, ok=False)
    feed_down = client.get(f"/api/devices/{HW}/scene?{QUERY}")

    # ok:TRUE and 90 seconds stale -- the fetch daemon was stopped, so nothing
    # ever wrote a failure. This is the fixture the whole expiry design exists
    # for, and revision 2 of the plan never generated one.
    _write_feed(cache_dir, NOW - 90.0, ok=True)
    feed_stale = client.get(f"/api/devices/{HW}/scene?{QUERY}")

    def body(resp) -> str:
        return json.dumps(resp.get_json(), separators=(",", ":"),
                          ensure_ascii=False, sort_keys=True)

    lines = [
        "// GENERATED by HomeScreen/scripts/dump_wire_fixture.py -- do not edit.",
        "//",
        "// The exact bytes the server emits. Regenerate with:",
        "//   venv/bin/python scripts/dump_wire_fixture.py",
        "// tests/test_wire_contract.py fails if this drifts from the server.",
        "#pragma once",
        "",
        f"inline constexpr char kWireAssigned[] = R\"JSON({body(assigned)})JSON\";",
        f"inline constexpr char kWireUnassigned[] = R\"JSON({body(unassigned)})JSON\";",
        f"inline constexpr char kWirePending[] = R\"JSON({body(pending)})JSON\";",
        f"inline constexpr char kWireDropped[] = R\"JSON({body(dropped)})JSON\";",
        "",
        "// ok:false, data fresh -- a single upstream timeout. Must NOT blank.",
        f"inline constexpr char kWireFeedDown[] = R\"JSON({body(feed_down)})JSON\";",
        "// ok:TRUE, 90s stale -- the fetch daemon was stopped and nothing ever",
        "// wrote a failure. The only signal is feed_age_s. MUST expire.",
        f"inline constexpr char kWireFeedStale[] = R\"JSON({body(feed_stale)})JSON\";",
        "",
        "// Echoed verbatim in If-None-Match, HTTP quotes included.",
        f"inline constexpr char kWireAssignedEtag[] = "
        f"{json.dumps(assigned.headers['ETag'])};",
        f"inline constexpr int kWireAssignedPollSeconds = "
        f"{assigned.headers['X-Poll-Seconds']};",
        "",
        "// Where the fixture traffic is. A test whose radar centre is anywhere",
        "// else clips every target off the dial and proves nothing.",
        f"inline constexpr double kWireHomeLat = {HOME_LAT};",
        f"inline constexpr double kWireHomeLon = {HOME_LON};",
        "",
    ]
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", type=pathlib.Path,
                    default=ROOT / "firmware" / "test" / "fixtures_wire.h")
    args = ap.parse_args()
    build(args.out)
    print(f"wrote {args.out}")
